.PHONY: clean

clean:
	cd ./errorThread && make clean
	cd ./thread && make clean
	cd ./serverApplication && make clean
	cd ./reactor && make clean
	cd ./configuration && make clean
	cd ./asyncLogger && make clean
	cd ./application && make clean
	cd ./loggingConfigurator && make clean
	cd ./logger && make clean
	cd ./dns && make clean
